DROP SEQUENCE IF EXISTS ITEM_SEQ;
DROP TABLE IF EXISTS ITEM;

CREATE SEQUENCE ITEM_SEQ;

CREATE TABLE ITEM
(
    id    BIGINT DEFAULT ITEM_SEQ.nextval PRIMARY KEY,
    name  VARCHAR(20) NOT NULL,
    price INT         NOT NULL,
    stock INT    DEFAULT 0,
    type  VARCHAR(20) NOT NULL
);